# -*- coding: utf-8 -*-
"""Análise SEO

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FpFCSJ4vMZuDyc7KdEpK_nZI9BaFbo78
"""

!pip install request beatifulsoup4
import requests
from bs4 import BeautifulSoup

import requests
from bs4 import BeautifulSoup

def analisador_URL (palavra):
  pontos = 0
  URL = input('Cole a URL: ')
  resultados = {}
  for urls in URL:
    urls = urls.strip()
    response = requests.get(urls)
    soup = BeautifulSoup(response.text, 'html.parser')
    h1 = soup.find('h1')
    if h1:
      pontos += 15
      texto_h1 = h1.get_text().lower()
      status_h1 = f'Sim'
      if palavra in texto_h1:
        pontos += 15
        palavra_h1 = f'Sim'
      else:
          palavra_h1 = 'Não'
      if palavra in texto_h1 [:30]:
        pontos += 10
        inicio_h1 = 'Sim'
      else:
          inicio_h1 = 'Não'
    else:
        status_h1 = 'Não'

    resultados[urls] = {
        'H1 encontrado?': status_h1,
        'Palavra-chave no H1?': palavra_h1,
        'Palavra-chave no início do H1?' : inicio_h1,}
  for enderecos, dados in resultados.items():
    print('\nURL:',enderecos)
    print('\nAnalise:',dados)
    return pontos
# ---------------------------------
def analisador_titulo(palavra):
  pontos = 0
  title = str(input('Insira o título')).strip().lower()
  titulos = {}
  for marcador in title:
      marcador = marcador.strip()
      tamanho = len(marcador)
      if palavra in marcador:
        pontos += 20
        titulo_palavra = 'Sim'
      else:
          titulo_palavra = 'Não'
      if palavra in marcador [:30]:
        pontos += 10
        palavra_comeco = 'Sim '
      else:
        palavra_comeco = 'Não'
      if tamanho >= 60:
        tamanho_titulo = f'{tamanho} caracteres, o título é muito grande para SEO.'
      else:
        pontos += 10
        tamanho_titulo = f'{tamanho} caracteres, tamanho adequado para SEO.'

      titulos [marcador] = {
            'A palavra-chave está no título?':titulo_palavra,
            'A palavra-chave está no começo do título?':palavra_comeco,
            'Qual o tamanho do título?': tamanho_titulo}
  for marcador, dados in titulos.items():
    print('\n',marcador)
    print('\n',dados)
    return pontos
# -----------------------------
def analisador_meta_descricao(palavra):
  pontos = 0
  meta_descrição = str(input('Digite cada meta descrição')).strip().lower()
  descricao = {}
  for contador in meta_descrição:
    contador = contador.strip()
    tamanho_meta = len(contador)
    if tamanho_meta >= 160:
      pontos += 10
      meta_tamanho = f'Meta descrição muito longa. {tamanho_meta} caracteres'
    elif tamanho_meta <= 80:
      meta_tamanho = f'Meta descrição muito curta. {tamanho_meta} caracteres'
    else:
      meta_tamanho = f'Meta descrição com tamanho certo. {tamanho_meta} caracteres'
    if palavra in contador:
      pontos += 10
      meta_palavra = 'Sim'
    else:
      meta_palavra = 'Não'

    descricao [contador] = {
        'Qual o tamanho da meta descrição?': meta_tamanho,
        'A palavra-chave está na meta descrição?': meta_palavra}
  for marcador, dados in descricao.items():
    print('\nMeta Descrição:',marcador)
    print('\nAnálise:',dados)
    return pontos

def auditoria_completa(pl):
  pontos = (analisador_URL(pl)+
  analisador_titulo(pl)+
  analisador_meta_descricao(pl))
  print(f'Pontuação SEO {pontos}/100')
  if pontos <= 40:
    print('SEO Ruim')
  elif pontos >= 70 or pontos == 100:
    print('SEO Bom')
  else:
    print('SEO Médio')

menu = {'1': analisador_URL,
        '2':analisador_titulo,
        '3':analisador_meta_descricao,
        '4':auditoria_completa}

while True:
  print('[1] Verificar URL')
  print('[2] Verificar Título')
  print('[3] Verificar Meta descrição')
  print('[4] Auditoria completa de SEO')
  print('[5] Sair')

  opção = input('Escolha uma opção: ')
  if opção == '5':
    print('Encerrando programa...')
    break
  if opção in menu:
    pl = str(input('Digite a palavra-chave ')).strip().lower()
    menu[opção](pl)
  else:
    print('Opção inválida')

